server:
  port: 8080
spring:
  application:
    name: gate
  cloud:
    zookeeper:
      connect-string: ${server:master}:2181
      discovery:
        enabled: true
        root: /services
        instance-id: ${spring.application.name}:${server.port}


configure:
  path:
    exclude:
      - /user/login
      - /user/register


